# frontend/Dockerfile
FROM node:24-alpine

WORKDIR /app

# Instalar dependencias de construcción
RUN apk add --no-cache \
    python3 \
    make \
    g++

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# Exponer puerto
EXPOSE 3000

# Comando para producción
#CMD ["npm", "start"]

# Para desarrollo (sobrescribir en docker-compose)
 CMD ["npm", "run", "dev"]